Tezos Node: https://rpc.tzbeta.net
Oven Address: KTXXXXXXXXXXXXXXXXXXXXXX
Alert Percentage: 250
Refresh Rate (seconds): 600
Continuous Alert: True

Twilio SID: 
Twilio Auth Token: 
Twilio Phone Number: XXXXXXXXXX
Recipient Phone Number: XXXXXXXXXX
