Tezos Node: https://rpc.tzbeta.net
Oven Address: KTXXXXXXXXXXXXXXXXXXXXXX
Alert Percentage: 250
Refresh Rate (seconds): 600

Twilio SID: 
Twilio Auth Token: 
Twilio Phone Number: 
Recipient Phone Number: 
